from models import Alert, Listing, User

SEED_LISTINGS = [
    {
        "title": "Nintendo 64 Funtastic Ice Blue — Boîte complète",
        "title_en": "Nintendo 64 Funtastic Ice Blue — Complete in Box",
        "description": "Console N64 édition Funtastic Ice Blue en excellent état. Boîte, manette et câbles d'origine. Rare pièce de collection.",
        "description_en": "N64 Funtastic Ice Blue edition in excellent condition. Original box, controller and cables. Rare collector piece.",
        "console": "Nintendo 64",
        "brand": "Nintendo",
        "listing_type": "sell",
        "condition": "Excellent",
        "price": 420.0,
        "location": "Paris, France",
        "image_url": "https://picsum.photos/seed/n64",
        "is_collectible": True,
        "is_featured": True,
        "source": "RetroPulse",
    },
    {
        "title": "PlayStation 2 Slim SCPH-90004 — Recherche",
        "title_en": "PlayStation 2 Slim SCPH-90004 — Wanted",
        "description": "Je recherche une PS2 Slim en bon état avec manette DualShock 2. Budget flexible selon état.",
        "description_en": "Looking for a PS2 Slim in good condition with DualShock 2 controller. Flexible budget depending on condition.",
        "console": "PlayStation 2",
        "brand": "Sony",
        "listing_type": "buy",
        "condition": "Bon",
        "price": 80.0,
        "location": "Lyon, France",
        "image_url": "https://picsum.photos/seed/ps2",
        "is_collectible": False,
        "is_featured": True,
        "source": "RetroPulse",
    },
    {
        "title": "Sega Dreamcast — Édition limitée Sports",
        "title_en": "Sega Dreamcast — Sports Limited Edition",
        "description": "Dreamcast édition Sports avec VMU et jeux inclus. Fonctionne parfaitement, légères traces d'usure.",
        "description_en": "Sports edition Dreamcast with VMU and games included. Works perfectly, slight wear marks.",
        "console": "Dreamcast",
        "brand": "Sega",
        "listing_type": "sell",
        "condition": "Très bon",
        "price": 185.0,
        "location": "Bruxelles, Belgique",
        "image_url": "https://picsum.photos/seed/dreamcast",
        "is_collectible": True,
        "is_featured": True,
        "source": "LeBonCoin",
    },
    {
        "title": "Super Nintendo SNES — Set complet 2 manettes",
        "title_en": "Super Nintendo SNES — Complete Set with 2 Controllers",
        "description": "SNES PAL avec 2 manettes originales et câbles. Console testée, image et son parfaits.",
        "description_en": "PAL SNES with 2 original controllers and cables. Console tested, perfect picture and sound.",
        "console": "Super Nintendo",
        "brand": "Nintendo",
        "listing_type": "sell",
        "condition": "Bon",
        "price": 145.0,
        "location": "Marseille, France",
        "image_url": "https://picsum.photos/seed/snes",
        "is_collectible": False,
        "is_featured": False,
        "source": "eBay",
    },
    {
        "title": "Xbox Original — Crystal Edition transparente",
        "title_en": "Original Xbox — Crystal Clear Edition",
        "description": "Xbox Crystal Edition ultra rare. Coque transparente, disque dur 120 Go modifié. Pièce museum.",
        "description_en": "Ultra rare Crystal Edition Xbox. Transparent shell, modded 120GB hard drive. Museum piece.",
        "console": "Xbox Original",
        "brand": "Microsoft",
        "listing_type": "sell",
        "condition": "Excellent",
        "price": 650.0,
        "location": "Berlin, Allemagne",
        "image_url": "https://picsum.photos/seed/xbox",
        "is_collectible": True,
        "is_featured": True,
        "source": "RetroPulse",
    },
    {
        "title": "GameCube Indigo — Recherche avec manette WaveBird",
        "title_en": "Indigo GameCube — Wanted with WaveBird Controller",
        "description": "Recherche GameCube Indigo en bon état. Manette WaveBird sans fil souhaitée en bonus.",
        "description_en": "Looking for Indigo GameCube in good condition. WaveBird wireless controller as bonus.",
        "console": "GameCube",
        "brand": "Nintendo",
        "listing_type": "buy",
        "condition": "Bon",
        "price": 120.0,
        "location": "Genève, Suisse",
        "image_url": "https://picsum.photos/seed/gamecube",
        "is_collectible": False,
        "is_featured": False,
        "source": "RetroPulse",
    },
    {
        "title": "Neo Geo AES — Console + 3 jeux originaux",
        "title_en": "Neo Geo AES — Console + 3 Original Games",
        "description": "Neo Geo AES avec Metal Slug, Samurai Shodown II et King of Fighters '98. Cartouches originales.",
        "description_en": "Neo Geo AES with Metal Slug, Samurai Shodown II and King of Fighters '98. Original cartridges.",
        "console": "Neo Geo AES",
        "brand": "SNK",
        "listing_type": "sell",
        "condition": "Excellent",
        "price": 1200.0,
        "location": "Tokyo, Japon",
        "image_url": "https://picsum.photos/seed/neogeo",
        "is_collectible": True,
        "is_featured": True,
        "source": "Yahoo Auctions",
    },
    {
        "title": "PlayStation 1 — Net Yaroze (Dev Kit)",
        "title_en": "PlayStation 1 — Net Yaroze (Dev Kit)",
        "description": "PS1 Net Yaroze kit de développement complet. Documentation et câbles inclus. Grail absolu.",
        "description_en": "Complete PS1 Net Yaroze development kit. Documentation and cables included. Absolute grail.",
        "console": "PlayStation 1",
        "brand": "Sony",
        "listing_type": "sell",
        "condition": "Excellent",
        "price": 890.0,
        "location": "Londres, UK",
        "image_url": "https://picsum.photos/seed/ps1",
        "is_collectible": True,
        "is_featured": True,
        "source": "RetroPulse",
    },
    {
        "title": "Atari 2600 — Woodgrain original 1977",
        "title_en": "Atari 2600 — Original 1977 Woodgrain",
        "description": "Atari 2600 six-switch woodgrain de 1977. Fonctionnel avec joysticks et 10 cartouches.",
        "description_en": "1977 six-switch woodgrain Atari 2600. Working with joysticks and 10 cartridges.",
        "console": "Atari 2600",
        "brand": "Atari",
        "listing_type": "sell",
        "condition": "Correct",
        "price": 95.0,
        "location": "San Francisco, USA",
        "image_url": "https://picsum.photos/seed/atari",
        "is_collectible": True,
        "is_featured": False,
        "source": "eBay",
    },
    {
        "title": "Nintendo Switch OLED — Édition Zelda TOTK",
        "title_en": "Nintendo Switch OLED — Zelda TOTK Edition",
        "description": "Switch OLED édition Tears of the Kingdom. Comme neuve, utilisée 2 semaines seulement.",
        "description_en": "Tears of the Kingdom edition Switch OLED. Like new, used only 2 weeks.",
        "console": "Nintendo Switch",
        "brand": "Nintendo",
        "listing_type": "sell",
        "condition": "Comme neuf",
        "price": 310.0,
        "location": "Montréal, Canada",
        "image_url": "https://picsum.photos/seed/switch",
        "is_collectible": False,
        "is_featured": False,
        "source": "RetroPulse",
    },
    {
        "title": "Sega Mega Drive — Recherche modèle japonais",
        "title_en": "Sega Mega Drive — Looking for Japanese Model",
        "description": "Recherche Mega Drive modèle japonais (MD1) avec manette 3 boutons originale.",
        "description_en": "Looking for Japanese Mega Drive model (MD1) with original 3-button controller.",
        "console": "Mega Drive",
        "brand": "Sega",
        "listing_type": "buy",
        "condition": "Bon",
        "price": 70.0,
        "location": "Barcelone, Espagne",
        "image_url": "https://picsum.photos/seed/megadrive",
        "is_collectible": True,
        "is_featured": False,
        "source": "RetroPulse",
    },
    {
        "title": "PlayStation 5 — Digital Edition CFI-1200",
        "title_en": "PlayStation 5 — Digital Edition CFI-1200",
        "description": "PS5 Digital Edition révision CFI-1200. Garantie restante 8 mois. Manette DualSense incluse.",
        "description_en": "PS5 Digital Edition CFI-1200 revision. 8 months warranty remaining. DualSense included.",
        "console": "PlayStation 5",
        "brand": "Sony",
        "listing_type": "sell",
        "condition": "Comme neuf",
        "price": 380.0,
        "location": "Amsterdam, Pays-Bas",
        "image_url": "https://picsum.photos/seed/ps5",
        "is_collectible": False,
        "is_featured": True,
        "source": "Marktplaats",
    },
    {
        "title": "Xbox Series X — Édition Halo Infinite",
        "title_en": "Xbox Series X — Halo Infinite Edition",
        "description": "Xbox Series X édition limitée Halo Infinite. Boîte collector complète, jamais ouverte.",
        "description_en": "Halo Infinite limited edition Xbox Series X. Complete collector box, never opened.",
        "console": "Xbox Series X",
        "brand": "Microsoft",
        "listing_type": "sell",
        "condition": "Neuf",
        "price": 750.0,
        "location": "Seattle, USA",
        "image_url": "https://picsum.photos/seed/xboxsx",
        "is_collectible": True,
        "is_featured": True,
        "source": "RetroPulse",
    },
    {
        "title": "Game Boy Color — Atomic Purple CIB",
        "title_en": "Game Boy Color — Atomic Purple CIB",
        "description": "Game Boy Color Atomic Purple Complete in Box. Écran parfait, son impeccable.",
        "description_en": "Atomic Purple Game Boy Color Complete in Box. Perfect screen, flawless sound.",
        "console": "Game Boy Color",
        "brand": "Nintendo",
        "listing_type": "sell",
        "condition": "Excellent",
        "price": 175.0,
        "location": "Osaka, Japon",
        "image_url": "https://picsum.photos/seed/gbc",
        "is_collectible": True,
        "is_featured": False,
        "source": "Mercari",
    },
    {
        "title": "Panasonic 3DO FZ-1 — Recherche",
        "title_en": "Panasonic 3DO FZ-1 — Wanted",
        "description": "Recherche console 3DO FZ-1 fonctionnelle. Pièce manquante pour ma collection rétro.",
        "description_en": "Looking for a working 3DO FZ-1 console. Missing piece for my retro collection.",
        "console": "3DO",
        "brand": "Panasonic",
        "listing_type": "buy",
        "condition": "Bon",
        "price": 200.0,
        "location": "Zurich, Suisse",
        "image_url": "https://picsum.photos/seed/3do",
        "is_collectible": True,
        "is_featured": False,
        "source": "RetroPulse",
    },
    {
        "title": "Nintendo Wii — White Bundle 2 manettes + Balance Board",
        "title_en": "Nintendo Wii — White Bundle 2 Controllers + Balance Board",
        "description": "Pack Wii complet avec 2 Wiimotes, Nunchuks et Balance Board. Idéal famille.",
        "description_en": "Complete Wii pack with 2 Wiimotes, Nunchuks and Balance Board. Perfect for family.",
        "console": "Nintendo Wii",
        "brand": "Nintendo",
        "listing_type": "sell",
        "condition": "Bon",
        "price": 65.0,
        "location": "Toulouse, France",
        "image_url": "https://picsum.photos/seed/wii",
        "is_collectible": False,
        "is_featured": False,
        "source": "LeBonCoin",
    },
]


def seed_database(db):
    if db.query(Listing).count() > 0:
        return

    demo_user = User(
        email="demo@retropulse.io",
        name="Alex Collector",
        password="demo123",
        plan="pro",
    )
    db.add(demo_user)
    db.flush()

    for item in SEED_LISTINGS:
        db.add(Listing(**item))

    db.add(Alert(user_id=demo_user.id, console="Nintendo 64", max_price=400.0, listing_type="sell"))
    db.add(Alert(user_id=demo_user.id, console="Dreamcast", max_price=200.0, listing_type="sell"))
    db.commit()
